ShopSoftWare/Controllers/ADUserController.cs
using Models.DAO;
using Models.EF;
using ShopSoftWare.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;

namespace ShopSoftWare.Controllers
{
    public class ADUserController : BaseController
    {
        // GET: ADUser
        public ActionResult Index(string searchString, int page = 1, int pageSize = 6)
        {
            var daoUser = new UserDao();
            var modelListuser = daoUser.GetAllPagingUser(searchString, page, pageSize);
            ViewBag.SearchString = searchString;
            return View(modelListuser);
        }

        [HttpGet]
        public ActionResult CreateUser()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateUser(CreateUser model)
        {
            if (ModelState.IsValid)
            {
                var userDao = new UserDao();
                var userNew = new User();
                userNew.Username = model.Username;
                userNew.Password = model.Password;
                userNew.Name = model.Name;
                userNew.Address = model.Address;
                userNew.Phone = model.Phone;
                userNew.Email = model.Email;
                userNew.CreateDate = DateTime.Now;
                userNew.ModifiDate = DateTime.Now;
                userNew.Permission = model.Permission;
                userNew.Status = model.Status;

                if (userDao.CheckUsername(model.Username.ToLower()))
                {
                    var res = userDao.InsertUser(userNew);

                    if (res == true)
                    {
                        ModelState.AddModelError("", "Thêm tài khoản thành công !\nĐang chuyển đến trang đăng nhập.");                        
                        return Redirect("/admin/user");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Thêm tài khoản thất bại !");
                        //return Redirect("/admin/user/create");
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Tên tài khoản đã tồn tại.");
                }
            }
            return View();
        }

        [HttpGet]
        public ActionResult EditUser(long id)
        {
            var model = new UserDao().GetUserByID(id);
            var userEdit = new CreateUser();
            userEdit.Username = model.Username;
            userEdit.Password = model.Password;
            userEdit.RePassword = model.Password;
            userEdit.Name = model.Name;
            userEdit.Address = model.Address;
            userEdit.Phone = model.Phone;
            userEdit.Email = model.Email;
            userEdit.Permission = model.Permission;
            return View(userEdit);
        }

        [HttpPost]
        public ActionResult EditUser(CreateUser model)
        {
            if (ModelState.IsValid)
            {
                var userDao = new UserDao();
                var userNew = new User();

                userNew.ID = model.ID;
                userNew.Username = model.Username;
                userNew.Password = model.Password;
                userNew.Name = model.Name;
                userNew.Address = model.Address;
                userNew.Phone = model.Phone;
                userNew.Email = model.Email;
                userNew.ModifiDate = DateTime.Now;
                userNew.Permission = model.Permission;

                var res = userDao.UpdateUser(userNew);
                if (res == true)
                {
                    ModelState.AddModelError("", "Cập nhật tài khoản thành công !\nĐang chuyển đến trang đăng nhập.");                    
                    return Redirect("/admin/user");
                }
                else
                {
                    ModelState.AddModelError("", "Cập nhật tài khoản thất bại !");
                    //return Redirect("/admin/user/create");
                }
            }
            return View();
        }

        [HttpDelete]
        public ActionResult DeleteUser(long id)
        {
            var res = new UserDao().DeleteUserByID(id);
            return Redirect("/admin/user");
        }

        [HttpPost]
        public JsonResult ChangeStatusUser(long id)
        {
            var res = new UserDao().ChangeStatus(id);
            return Json(new { status = res });
        }

    }
}

ShopSoftWare/Views/ADUser/CreateUser.cshtml
@model ShopSoftWare.Common.CreateUser

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@section titlePage{Thêm mới tài khoản}


<div class="container">
    @using (Html.BeginForm("CreateUser", "ADUser", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4 style="text-transform:uppercase">Thêm mới tài khoản</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Username, new { htmlAttributes = new { @class = "form-control fix-size-textbox" }, style = "width: 400px;" })
                    <br />
                    @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Name, new { htmlAttributes = new { @class = "form-control fix-size-textbox" }, style = "width: 400px;" })
                    <br />
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-10">
                    @Html.PasswordFor(model => model.Password, new { htmlAttributes = new { @class = "form-control fix-size-textbox" }, style = "width: 400px;" })
                    <br />
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.RePassword, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-10">
                    @Html.PasswordFor(model => model.RePassword, new { htmlAttributes = new { @class = "form-control fix-size-textbox" }, style = "width: 400px;" })
                    <br />
                    @Html.ValidationMessageFor(model => model.RePassword, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Address, new { htmlAttributes = new { @class = "form-control fix-size-textbox" }, style = "width: 400px;" })
                    <br />
                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control fix-size-textbox" } })
                    <br />
                    @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Email, new { htmlAttributes = new { @class = "form-control fix-size-textbox" }, style = "width: 400px;" })
                    <br />
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Permission, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.CheckBoxFor(model => model.Permission)
                        <br />
                        @Html.ValidationMessageFor(model => model.Permission, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.CheckBoxFor(model => model.Status)
                        <br />
                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-6">
                    <button class="btn btn-success btn-block" type="submit">Thêm mới tài khoản</button>
                </div>
            </div>
            <br />
            <br />
        </div>
    }
</div>

ShopSoftWare/Views/ADUser/EditUser.cshtml
@model ShopSoftWare.Common.CreateUser

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@section titlePage{Sửa thông tin tài khoản}


<div class="container">
    @using (Html.BeginForm("EditUser", "ADUser", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4 style="text-transform:uppercase">Sửa thông tin tài khoản</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Username, new { htmlAttributes = new { @class = "form-control fix-size-textbox" }, style = "width: 400px;" })
                    <br />
                    @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Name, new { htmlAttributes = new { @class = "form-control fix-size-textbox" }, style = "width: 400px;" })
                    <br />
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-10">
                    @Html.PasswordFor(model => model.Password, new { htmlAttributes = new { @class = "form-control fix-size-textbox" }, style = "width: 400px;" })
                    <br />
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.RePassword, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-10">
                    @Html.PasswordFor(model => model.RePassword, new { htmlAttributes = new { @class = "form-control fix-size-textbox" }, style = "width: 400px;" })
                    <br />
                    @Html.ValidationMessageFor(model => model.RePassword, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Address, new { htmlAttributes = new { @class = "form-control fix-size-textbox" }, style = "width: 400px;" })
                    <br />
                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control fix-size-textbox" } })
                    <br />
                    @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Email, new { htmlAttributes = new { @class = "form-control fix-size-textbox" }, style = "width: 400px;" })
                    <br />
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Permission, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.CheckBoxFor(model => model.Permission)
                        <br />
                        @Html.ValidationMessageFor(model => model.Permission, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>         

            <div class="form-group">
                <div class="col-md-offset-2 col-md-6">
                    <button class="btn btn-danger btn-block" type="submit">Sửa tài khoản</button>
                </div>
            </div>
            <br />
            <br />
        </div>
    }

    <div>
        <a class="btn btn-warning" href="/admin/user">Hủy bỏ</a>
    </div>
</div>

ShopSoftWare/Views/ADUser/Index.cshtml
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@section titlePage {Quản lý người dùng}

@model PagedList.IPagedList<Models.EF.User>
@using PagedList.Mvc;

@section fixPage{
    <style>
        .pagination-container ul li a {
            padding: 5px 10px;
            margin: 0px 5px;
            color: #0984e3;
            -webkit-box-shadow: 3px 3px 5px 0px rgba(0,0,0,0.75);
            -moz-box-shadow: 3px 3px 5px 0px rgba(0,0,0,0.75);
            box-shadow: 3px 3px 5px 0px rgba(0,0,0,0.75);
            background-color: #dcdde1;
        }
    </style>
}

@section stylePage{
    <link rel="stylesheet" href="/Assets/admin/css/stytleAccount.css">
}

@section jsFooter{
    <script src="/Assets/admin/js/changeStatusUser.js"></script>
}

<div class="search-add">
    <div>
        @using (Html.BeginForm("Index", "ADUser", FormMethod.Get))
        {
            <input type="text" value="@ViewBag.SearchString" placeholder="Tìm kiếm" name="searchString" class="search-text">
            <button type="submit" class="btn btn-success search-btn">Tìm kiếm</button>
        }
    </div>
    <div class="btn-add">
        <a href="/admin/user/create" class="btn btn-primary">Thêm mới tài khoản</a>
    </div>
</div>
<br>
<!-- Begin Content -->
<div>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Tên tài khoản</th>
                <th>Tên người dùng</th>
                <th>Email</th>
                <th>Số điện thoại</th>
                <th>Ngày tạo</th>
                <th>Sửa lần cuối</th>
                <th>Trạng thái</th>
                <th>Quyền hạn</th>
                <th>Tác vụ</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var items in Model)
            {
                <tr id="row_@items.ID">
                    <td>@items.Username</td>
                    <td>@items.Name</td>
                    <td>@items.Email</td>
                    <td>@items.Phone</td>
                    <td>@items.CreateDate.ToString()</td>
                    <td>@(items.ModifiDate.ToString() == null ? "Chưa thay đổi" : items.ModifiDate.ToString() )</td>
                    <td><a href="#" class="text-success btn-active" data-id="@items.ID">@(items.Status ? "Kích hoạt" : "Khóa")</a></td>
                    <td>@(items.Permission ? "admin" : "user")</td>
                    <td>
                        <a href="/admin/user/edit/@items.ID" class="btn btn-warning">Sửa</a> -
                        @Ajax.ActionLink("Xóa", "DeleteUser", new { @id = items.ID },
                                     new AjaxOptions
                                     {
                                         Confirm = "Bạn có chắc muốn xóa ?\nHãy cân nhắc trước khi xóa vì việc này rất nguy hiểm đến dữ liệu của bạn !",
                                         OnComplete = "$(row_" + items.ID + ").remove()",
                                         HttpMethod = "Delete"
                                     }, new { @class = "btn btn-danger" } )                     
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <br />
    <div style="margin-left:20px" class="text-center">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, @searchString = @ViewBag.SearchString }))
    </div>
    <br />
</div>