ShopSoftWare/Controllers/ADLoginController.cs
using Models.DAO;
using ShopSoftWare.Common;
using ShopSoftWare.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopSoftWare.Controllers
{
    public class ADLoginController : Controller
    {
        // GET: ADLogin
        public ActionResult Login(LoginAdmin model)
        {
            if (ModelState.IsValid)
            {
                var userDao = new UserDao();
                var res = userDao.LoginSystem(model.username, model.password);

                if (res == 1)
                {
                    var userSession = new UserLogin();
                    var inforUser = userDao.GetUserByUsernameAndPass(model.username, model.password);
                    userSession.Username = inforUser.Username;
                    userSession.Password = inforUser.Password;
                    userSession.Name = inforUser.Name;

                    Session.Add(CommonConstants.ADMIN_SESSION, userSession);

                    return Redirect("/admin/product");
                }
                else if (res == 0)
                {
                    ModelState.AddModelError("", "Tài khoản không tồn tại.");
                }
                else if (res == -1)
                {
                    ModelState.AddModelError("", "Tài khoản đang bị khóa.");
                }
                else if (res == -3)
                {
                    ModelState.AddModelError("", "Tài khoản của bạn không có quyền hạn để đăng nhập vào trang này.");
                }
                else if (res == -2)
                {
                    ModelState.AddModelError("", "Thông tin tài khoản hoặc mật khẩu không đúng.");
                }
            }

            return View("Login");
        }


        public ActionResult Logout()
        {
            Session[CommonConstants.ADMIN_SESSION] = null;
            return Redirect("/admin");
        }
    }
}

ShopSoftWare/Controllers/USHomeController.cs
using Models.DAO;
using ShopSoftWare.Common;
using ShopSoftWare.Models;
using System;
using System.Collections.Generic;
using System.IO.Ports;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopSoftWare.Controllers
{
    public class USHomeController : Controller
    {
        // GET: USHome
        public ActionResult Index()
        {
            var dao = new ProductDao();
            ViewBag.ListWin = dao.ListProductForHome("DM01");
            ViewBag.ListOffice = dao.ListProductForHome("DM02");
            ViewBag.ListGame = dao.ListProductForHome("DM03");
            ViewBag.ListVirus = dao.ListProductForHome("DM04");
            return View();
        }

        [ChildActionOnly]
        public ActionResult Footer()
        {
            var modelFooter = new FooterDao().GetFooterByID(1);
            return PartialView(modelFooter);
        }

        [ChildActionOnly]
        public ActionResult Cart()
        {
            var cartSession = Session[CommonConstants.CART_SECSSION];
            var listCart = new List<CartItem>();
            if (cartSession != null)
            {
                listCart = (List<CartItem>)cartSession;
            }

            var customerSession = Session[CommonConstants.CUSTOMER_SECSION];
            var customer = new Customer();
            if(customerSession != null)
            {
                customer = (Customer)customerSession;
            }

            ViewBag.InforCustomer = customer;

            return PartialView(listCart);
        }
    }
}

ShopSoftWare/Views/Shared/Cart.cshtml
@model List<ShopSoftWare.Models.CartItem>

@{ 
    var totalProduct = 0;
    foreach( var items in Model)
    {
        totalProduct += items.quantity;
    }

    var customer = (ShopSoftWare.Models.Customer)ViewBag.InforCustomer;
}
<div>
    <span></span>
</div>
<div class="account-cart">
    @if (customer.Name != null)
    {
        <p>@customer.Name</p>
        <a href="/gio-hang" class="nav-link">
            <img src="/Assets/client/images/icon-cart.png" alt="cart" height="35">
            @if (Model.Count > 0)
            {
                <span class="badge badge-secondary bg-danger">@totalProduct</span>
            }
            else
            {
                <span class="badge badge-secondary bg-danger">0</span>
            }
        </a>
        <a href="/dang-xuat">Đăng xuất</a>
    }
    else
    {
        <p><a href="/dang-nhap">Đăng nhập</a></p>
        <a href="/gio-hang" class="nav-link">
            <img src="/Assets/client/images/icon-cart.png" alt="cart" height="35">
            @if (Model.Count > 0)
            {
                <span class="badge badge-secondary bg-danger">@totalProduct</span>
            }
            else
            {
                <span class="badge badge-secondary bg-danger">0</span>
            }
        </a>
        <a href="/dang-ky">Đăng ký</a>
    }

</div>

ShopSoftWare/Views/Shared/Footer.cshtml
@model Models.EF.Footer

<div class="col-md-6 col-12">
    <h4 class="title-footer">Hỗ trợ khách hàng</h4>
    <div class="link-customer">
        <p><a href="#">Hướng dẫn mua hàng</a></p>
        <p><a href="#">Hình thức thanh toán</a></p>
        <p><a href="#">Chính sách đổi trả</a></p>
        <p> <a href="#">Câu hỏi thường gặp</a></p>
        <p><a href="#">Hướng dẫn mua hàng</a></p>
        <p><a href="#">Điều khoản & Điều kiện</a></p>
        <p><a href="#">Giới thiệu</a></p>
    </div>
</div>

<div class="col-md-6 col-12">
    <h4 class="title-footer">Thông tin liên hệ</h4>
    <div class="information-shop">
        <div>
            <p class="title-information">Địa chỉ: </p>
            <p class="content-information">@Model.Address</p>
        </div>
        <div>
            <p class="title-information">Điện thoại: </p>
            <p class="content-information">@Model.Phone</p>
        </div>
        <div>
            <p class="title-information">Email: </p>
            <p class="content-information">@Model.Email</p>
        </div>
        <div>
            <p class="title-information">Ngày/Giờ làm việc: </p>
            <p class="content-information">
                @Model.DayWorkforWeek / @Model.TimeWork
            </p>
        </div>
    </div>
</div>

ShopSoftWare/Views/Shared/_LayoutAdmin.cshtml
@{ 
    var adminSession = (ShopSoftWare.Common.UserLogin) Session[ShopSoftWare.Common.CommonConstants.ADMIN_SESSION];
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/2cd2adc0a3.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="/Assets/admin/css/bootstrap.css">
    <script src="/Assets/admin/js/jquery-3.5.0.min.js"></script>
    <script src="/Assets/admin/js/jquery.unobtrusive-ajax.js"></script>
    <link rel="stylesheet" href="/Assets/admin/css/stytle.css">
    <link href="/Assets/favicon.ico" rel="shortcut icon" />
    @RenderSection("stylePage", required: false)
    @RenderSection("fixsizetextbox", required: false)
    @RenderSection("fixPage", required: false)
    <title>@RenderSection("titlePage", required: true)</title>
</head>
<body>
    <div class="header">
        <div class="header-logo">
            <i class="far fa-arrow-alt-circle-left"></i>
            <a href="/trang-chu">Quay lại về Website</a>
            <img src="/Assets/admin/image/logo.png" alt="logo">
        </div>
        <div class="header-content">
            <span>Cheap software is an indispensable thing</span>
        </div>
        <div class="header-menu">
            @if (adminSession != null)
            {
                <ul>
                    <li>@adminSession.Name</li>
                    <li>@Html.ActionLink("Đăng xuất", "Logout", "ADLogin")</li>
                </ul>
            }
        </div>
    </div>

    <hr class="my-2">

    <div class="contain">
        <div class="menu">
            <ul>
                <li class="product"><a href="/admin/product">Sản phẩm</a></li>
                <li class="product-category"><a href="/admin/category">Danh mục sản phẩm</a></li>
                <li class="manager-footer"><a href="/admin/footer">Thông tin liên hệ</a></li>
                <li class="manager-order"><a href="/admin/order">Đơn hàng</a></li>
                <li class="account"><a href="/admin/user">Tài khoản</a></li>
            </ul>
        </div>
        <div class="content">
            @RenderBody()
        </div>
    </div>

    <hr class="my-2" style="clear: both;">

    @RenderSection("jsFooter", required:false)
    
</body>
</html>

ShopSoftWare/Views/Shared/_LayoutUser.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css">
    <link rel="stylesheet" href="/Assets/client/css/bootstrap.css">
    <link rel="stylesheet" href="/Assets/client/css/stytle.css">
    <script src="/Assets/client/js/jquery-3.5.0.min.js"></script>
    <link href="/Assets/favicon.ico" rel="shortcut icon" />

    @RenderSection("stylePage", required: false)
    @RenderSection("fixPage", required: false)

    <title>@RenderSection("titlePage", required: true)</title>
</head>
<body>
    <header class="header-content">
        <div class="container-fluid">
            @{ Html.RenderAction("Cart", "USHome"); }
        </div>
    </header>

    <hr class="my-2">

    <nav>
        <input type="checkbox" id="check">
        <label for="check">
            <i class="fas fa-bars" id="btn"></i>
            <i class="fas fa-times" id="cancel"></i>
        </label>
        <img src="/Assets/client/images/logo.png" class="img-fluid">
        <ul>
            <li><a href="/trang-chu"><i class="fas fa-home icon-menu"></i>Trang chủ</a></li>
            <li><a href="/key-windows"><i class="fab fa-windows icon-menu"></i>Bản quyền Windows</a></li>
            <li><a href="/key-office"> <i class="fas fa-briefcase icon-menu"></i>Bản quyền Office</a></li>
            <li><a href="/key-game"><i class="fas fa-download icon-menu"></i>Bản quyền Game</a></li>
            <li><a href="/key-virus"><i class="fas fa-shield-alt icon-menu"></i>Bản quyền diệt Virus</a></li>
        </ul>
    </nav>

    <hr class="my-2 hr-menu-content" width="100%">

    @RenderSection("sologan", required: false)

    <br>

    <div class="container">
        @RenderBody()
    </div>

    <br>
    <hr class="my-2">

    <footer>
        <div class="row container">
            @{ Html.RenderAction("Footer", "USHome"); }
        </div>
    </footer>

    @RenderSection("jsFooter", required: false)
    @RenderSection("checkInformationCustomer", required: false)

</body>
</html>