ShopSoftWare/Models/LoginCustomer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ShopSoftWare.Models
{
    public class LoginCustomer
    {
        [Required(ErrorMessage = "Nhập tài khoản người dùng !")]
        public string username { get; set; }
        [Required(ErrorMessage = "Nhập mật khẩu người dùng !")]
        public string password { get; set; }
    }
}

ShopSoftWare/Controllers/USAccountController.cs
using Models.DAO;
using Models.EF;
using ShopSoftWare.Common;
using ShopSoftWare.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopSoftWare.Controllers
{
    public class USAccountController : Controller
    {
        [HttpGet]
        public ActionResult CreateAccount()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateAccount(string username, string name, string pass, string address, string phone, string email)
        {
            var daoUser = new UserDao();
            if (daoUser.CheckUsername(username))
            {
                var customer = new User();
                customer.Username = username;
                customer.Name = name;
                customer.Password = pass;
                customer.Address = address;
                customer.Phone = phone;
                customer.Email = email;
                customer.CreateDate = DateTime.Now;
                customer.Status = true;
                customer.Permission = false;

                var res = daoUser.InsertUser(customer);

                if (res == true)
                {
                    return Redirect("/dang-nhap");
                }
                else
                {
                    ModelState.AddModelError("", "Thêm tài khoản thất bại !\nHãy thử lại nếu còn gặp tình trạng này hãy liên hệ với chúng tôi");
                }
            }
            else
            {
                ModelState.AddModelError("", "Tên tài khoản đã tồn tại.");
            }

            return View();
        }

        public ActionResult LoginCustomer(LoginCustomer model)
        {
            if (ModelState.IsValid)
            {
                var userDao = new UserDao();
                var res = userDao.LoginCustomer(model.username, model.password);

                if (res == 1)
                {
                    var userSession = new Customer();
                    var inforUser = userDao.GetUserByUsernameAndPass(model.username, model.password);
                    userSession.Username = inforUser.Username;
                    userSession.Password = inforUser.Password;
                    userSession.Name = inforUser.Name;
                    userSession.Address = inforUser.Address;
                    userSession.Phone = inforUser.Phone;
                    userSession.Email = inforUser.Email;
                    Session.Add(CommonConstants.CUSTOMER_SECSION, userSession);

                    return Redirect("/trang-chu");
                }
                else if (res == 0)
                {
                    ModelState.AddModelError("", "Tài khoản không tồn tại.");
                }
                else if (res == -1)
                {
                    ModelState.AddModelError("", "Tài khoản đang bị khóa.");
                }
                else if (res == -2)
                {
                    ModelState.AddModelError("", "Thông tin tài khoản hoặc mật khẩu không đúng.");
                }
            }
            return View();
        }

        public ActionResult LogoutCustomer()
        {
            Session[CommonConstants.CUSTOMER_SECSION] = null;
            return Redirect("/trang-chu");
        }
    }
}

ShopSoftWare/Views/USAccount/CreateAccount.cshtml
@{
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

@section titlePage{Đăng ký thành viên}

@section jsFooter{
    <script src="/Assets/client/js/validateRegister.js"></script>
}

<h2 style="text-transform: uppercase; text-decoration: underline;">Đăng ký tài khoản</h2>
<div class="row" style="display: flex; justify-content: center;">
    <div class="form-group col-md-8 col-12">

        <br />
        <p class="text-danger">Các mục có dấu " * " là bắt buộc</p>
        <br />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @using (Html.BeginForm("CreateAccount", "USAccount", FormMethod.Post))
        {
            <label for="username" style="margin-top: 20px;">Tên tài khoản<span class="text-danger">*</span></label>
            <input type="text" name="username" id="username" placeholder="Nhập thông tin" class="form-control">
            <div class="errUsername text-danger"></div>

            <label for="name" style="margin-top: 20px;">Họ và tên<span class="text-danger">*</span></label>
            <input type="text" name="name" id="name" placeholder="Nhập thông tin" class="form-control">
            <div class="errName text-danger"></div>

            <label for="pass" style="margin-top: 20px;">Mật khẩu<span class="text-danger">*</span></label>
            <input type="password" name="pass" id="pass" placeholder="Nhập thông tin" class="form-control">
            <div class="errPass text-danger"></div>

            <label for="repass" style="margin-top: 20px;">Nhập lại mật khẩu<span class="text-danger">*</span></label>
            <input type="password" name="repass" id="repass" placeholder="Nhập thông tin" class="form-control">
            <div class="errRepass text-danger"></div>

            <label for="address" style="margin-top: 20px;">Địa chỉ<span class="text-danger">*</span></label>
            <input type="text" name="address" id="address" placeholder="Nhập thông tin" class="form-control">
            <div class="errAddress text-danger"></div>

            <label for="phone" style="margin-top: 20px;">Số điện thoại<span class="text-danger">*</span></label>
            <input type="text" name="phone" id="phone" placeholder="Nhập thông tin" class="form-control">
            <div class="errPhone text-danger"></div>

            <label for="email" style="margin-top: 20px;">Email<span class="text-danger">*</span></label>
            <input type="text" name="email" id="email" placeholder="Nhập thông tin" class="form-control">
            <div class="errEmail text-danger"></div>

            <br>
            <br>
            <button type="submit" class="btn btn-danger">Đăng ký tài khoản</button>
        }

    </div>

</div>

ShopSoftWare/Views/USAccount/LoginCustomer.cshtml
@model ShopSoftWare.Models.LoginCustomer
@{
    Layout = "/Views/Shared/_LayoutUser.cshtml";
}

@section titlePage{Đăng nhập}

<div class="">
    <h2 style="text-transform:uppercase; margin-top:10px;">Đăng nhập</h2>
    <br />
    <div class="row">
        <div class="col-md-6 col-12">
            @using (Html.BeginForm("LoginCustomer", "USAccount", FormMethod.Post))
            {
                <br />
                @Html.ValidationSummary(false, "", new { @class = "text-danger " })
                <br />
                <div class="form-group">
                    <label for="username">Tài khoản</label>
                    @Html.TextBoxFor(x => x.username, new { @class = "form-control ", @id = "username", @placeholder = "Tài khoản" })
                    <p class="err-user text-danger"></p>
                </div>

                <div class="form-group">
                    <label for="password">Mật khẩu</label>
                    @Html.PasswordFor(x => x.password, new { @class = "form-control ", @id = "password", @placeholder = "Mật khẩu" })
                    <p class="err-pass text-danger"></p>
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block my-5" id="login">Đăng nhập</button>
                </div>
            }
        </div>
        <div class="col-md-6 col-12" style="text-transform:uppercase; font-size:25px; text-align:center; margin-top:50px;">
            <p class="text-primary">Cám ơn bạn đã luôn đồng hành và tin cậy các sản phẩm tại cửa hàng.</p>
        </div>

    </div>
</div>