ShopSoftWare/Controllers/ADProductController.cs
using Models.DAO;
using Models.EF;
using ShopSoftWare.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopSoftWare.Controllers
{
    public class ADProductController : BaseController
    {
        // GET: ADProduct
        public ActionResult Index(string searchString, int page = 1, int pageSize = 6)
        {
            var daoProduct = new ProductDao();
            var model = daoProduct.GetAllPagingProduct(searchString, page, pageSize);
            ViewBag.SearchString = searchString;
            return View(model);
        }

        public void SetViewbag(string id = null)
        {
            var dao = new CategoryDao();
            ViewBag.IDCategory = new SelectList(dao.GetListCategory(), "IDCategory", "NameCategory", id);
        }

        [HttpGet]
        public ActionResult InsertProduct()
        {
            SetViewbag();
            return View();
        }

        [HttpPost]
        public ActionResult InsertProduct(Product model)
        {
            if (ModelState.IsValid)
            {
                var daoProduct = new ProductDao();
                model.CreateDate = DateTime.Now;
                var count = daoProduct.GetCountProduct();

                if (count < 9)
                {
                    model.IDProduct = "SP0" + (count + 1);
                }
                else if( count >= 10)
                {
                    model.IDProduct = "SP" + (count + 1);
                }
                
                var res = daoProduct.InsertProduct(model);

                if(res == true)
                {
                    return Redirect("/admin/product");
                }
                else
                {
                    ModelState.AddModelError("", "Thêm không thành công !");
                    //return Redirect("/admin/product/insert");
                }
            }
            SetViewbag();
            return View();
        }

        [HttpGet]
        public ActionResult EditProduct(string id)
        {
            var daoProduct = new ProductDao();
            var product = daoProduct.GetProductByID(id);
            SetViewbag(product.IDCategory);
            return View(product);
        }

        [HttpPost]
        public ActionResult EditProduct(Product entity)
        {
            if (ModelState.IsValid)
            {
               
                var res = new ProductDao().UpdateProduct(entity, CommonConstants.IDProduct);

                if(res == true)
                {
                    return Redirect("/admin/product");
                }
                else
                {
                    ModelState.AddModelError("", "Sửa không thành công.");                  
                }
            }
            return View();
        }

        [HttpDelete]
        public ActionResult DeleteProduct(string id)
        {
            new ProductDao().DeleteProductByID(id);
            return Redirect("/admin/product");
        }

    }
}

ShopSoftWare/Views/ADProduct/EditProduct.cshtml
@model Models.EF.Product

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";

}

@section titlePage {Sửa thông tin sản phẩm}

<div class="container">
    @using (Html.BeginForm("EditProduct", "ADProduct", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Sửa thông tin sản phẩm</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            @{
                ShopSoftWare.Common.CommonConstants.IDProduct = Model.IDProduct;
            }

            <div class="form-group">
                @Html.LabelFor(model => model.NameProduct, htmlAttributes: new { @class = "control-label col-md-8" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NameProduct, new { htmlAttributes = new { @class = "form-control" } })
                    <br />
                    @Html.ValidationMessageFor(model => model.NameProduct, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IDCategory, "Danh mục sản phẩm", htmlAttributes: new { @class = "control-label col-md-8" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.IDCategory, null, htmlAttributes: new { @class = "form-control" })
                    <br />
                    @Html.ValidationMessageFor(model => model.IDCategory, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-8" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    <br />
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Images, htmlAttributes: new { @class = "control-label col-md-8" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Images, new { htmlAttributes = new { @class = "form-control" } })
                    <br />
                    @Html.ValidationMessageFor(model => model.Images, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-8" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                    <br />
                    @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-8" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.CheckBoxFor(model => model.Status)
                        <br />
                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button class="btn btn-warning btn-block">Cập nhật thông tin sản phẩm</button>
                </div>
            </div>
        </div>
    }
    <br />
    <br />
    <div>
        <a href="/admin/product" class="btn btn-danger">Hủy bỏ thao tác</a>
    </div>
</div>

ShopSoftWare/Views/ADProduct/Index.cshtml
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    var categoryDao = new Models.DAO.CategoryDao();
}

@section titlePage{ Sản phẩm }

@using PagedList.Mvc;
@model PagedList.IPagedList<Models.EF.Product>


@section stylePage{
    <link rel="stylesheet" href="/Assets/admin/css/stytleProduct.css">
}

@section fixPage{
    <style>
        .pagination-container ul li a {
            padding: 5px 10px;
            margin: 0px 5px;
            color: #0984e3;
            -webkit-box-shadow: 3px 3px 5px 0px rgba(0,0,0,0.75);
            -moz-box-shadow: 3px 3px 5px 0px rgba(0,0,0,0.75);
            box-shadow: 3px 3px 5px 0px rgba(0,0,0,0.75);
            background-color: #dcdde1;
        }
    </style>
}

<div>
    <div class="search-add">
        <div>
            @using (Html.BeginForm("Index", "ADProduct", FormMethod.Get))
            {
                <input type="text" value="@ViewBag.SearchString" placeholder="Tìm kiếm theo tên sản phẩm" name="searchString" class="search-text">
                <button type="submit" class="btn btn-success search-btn">Tìm kiếm</button>
            }
        </div>
        <div class="btn-add">
            <a href="/admin/product/insert" class="btn btn-primary">Thêm mới sản phẩm</a>
        </div>
    </div>
    <br>
    <!-- Begin table -->
    <table class="table table-hover">
        <thead class="bg-info">
            <tr>
                <th>Mã sản phẩm</th>
                <th>Tên sản phẩm</th>
                <th>Tên danh mục</th>
                <th>Số lượng</th>
                <th>Tình trạng bán</th>
                <th>Đơn giá</th>
                <th>Ảnh</th>
                <th>Tác vụ</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var items in Model)
            {
                <tr id="row_@items.IDProduct">
                    <td>@items.IDProduct</td>
                    <td>@items.NameProduct</td>
                    <td>@categoryDao.GetNameCategoryByID(items.IDCategory)</td>
                    <td>
                        @if (items.Quantity <= 0)
                        {
                            <span class="text-danger">Hết hàng</span>
                        }
                        else
                        {
                            <span>@items.Quantity</span>
                        }
                    </td>
                    <td class="text-success">@(items.Status ? "Bán" : "Ngừng bán")</td>
                    <td>@(items.Price.Value.ToString() ==  null ? "Liên hệ" : items.Price.Value.ToString("N0") + " - VND" )</td>
                    <td><img class="img-fluid img-key-win" src="@items.Images" alt="@items.NameProduct"></td>
                    <td>
                        <a href="/admin/product/edit/@items.IDProduct" class="btn btn-warning">Sửa</a> -
                        @Ajax.ActionLink("Xóa", "DeleteProduct", new { @id = items.IDProduct },
                                     new AjaxOptions
                                     {
                                         Confirm = "Bạn có chắc muốn xóa ?\nHãy cân nhắc trước khi xóa vì việc này rất nguy hiểm đến dữ liệu của bạn !",
                                         OnComplete = "$(row_" + items.IDProduct + ").remove()",
                                         HttpMethod = "Delete"
                                     }, new { @class = "btn btn-danger" })
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <!-- End table -->

    <br />
    <div style="margin-left:20px" class="text-center">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, @searchString = @ViewBag.SearchString }))
    </div>

</div>

ShopSoftWare/Views/ADProduct/InsertProduct.cshtml
@model Models.EF.Product

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@section titlePage {Thêm mới sản phẩm}


<div class="container">
    @using (Html.BeginForm("InsertProduct", "ADProduct", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Thêm mới sản phẩm</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.NameProduct, htmlAttributes: new { @class = "control-label col-md-8" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NameProduct, new { htmlAttributes = new { @class = "form-control" } })
                    <br />
                    @Html.ValidationMessageFor(model => model.NameProduct, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IDCategory, "Danh mục sản phẩm", htmlAttributes: new { @class = "control-label col-md-8" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.IDCategory, null, htmlAttributes: new { @class = "form-control" })
                    <br />
                    @Html.ValidationMessageFor(model => model.IDCategory, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-8" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    <br />
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Images, htmlAttributes: new { @class = "control-label col-md-8" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Images, new { htmlAttributes = new { @class = "form-control" } })
                    <br />
                    @Html.ValidationMessageFor(model => model.Images, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-8" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                    <br />
                    @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-8" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.CheckBoxFor(model => model.Status)
                        <br />
                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button class="btn btn-success btn-block">Thêm mới mặt hàng</button>
                </div>
            </div>
        </div>
    }
</div>